Repository codesquad-member-2020/sidedish-06, pull requests merged in 2020-04, with the labels that each got.

#12 [iOS] 로그인 화면 구성
  .gitignore
  iOS/SideDishApp/SideDishApp.xcodeproj/project.pbxproj
  iOS/SideDishApp/SideDishApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/SideDishApp/SideDishApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/SideDishApp/SideDishApp.xcodeproj/project.xcworkspace/xcuserdata/adorabledy.xcuserdatad/UserInterfaceState.xcuserstate
  iOS/SideDishApp/SideDishApp.xcodeproj/xcuserdata/adorabledy.xcuserdatad/xcschemes/xcschememanagement.plist
  iOS/SideDishApp/SideDishApp/AppDelegate.swift
  iOS/SideDishApp/SideDishApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/SideDishApp/SideDishApp/Assets.xcassets/Contents.json
  iOS/SideDishApp/SideDishApp/Base.lproj/LaunchScreen.storyboard
  iOS/SideDishApp/SideDishApp/Base.lproj/Main.storyboard
  iOS/SideDishApp/SideDishApp/Info.plist
  iOS/SideDishApp/SideDishApp/LoginViewController.swift
  iOS/SideDishApp/SideDishApp/SceneDelegate.swift
  iOS/SideDishApp/SideDishApp/ViewController.swift
Labels: iOS

#16 [iOS] 셀에 서버 데이터 바인딩
  iOS/SideDishApp/SideDishApp.xcodeproj/project.pbxproj
  iOS/SideDishApp/SideDishApp.xcodeproj/project.xcworkspace/xcuserdata/adorabledy.xcuserdatad/UserInterfaceState.xcuserstate
  iOS/SideDishApp/SideDishApp/Base.lproj/Main.storyboard
  iOS/SideDishApp/SideDishApp/Entry/AppDelegate.swift
  iOS/SideDishApp/SideDishApp/Entry/SceneDelegate.swift
  iOS/SideDishApp/SideDishApp/Models/AllMenu.swift
  iOS/SideDishApp/SideDishApp/Models/MenuDetail.swift
  iOS/SideDishApp/SideDishApp/Utilities/Networking/NetworkErrorCase.swift
  iOS/SideDishApp/SideDishApp/Utilities/Networking/NetworkManager.swift
  iOS/SideDishApp/SideDishApp/Utilities/Networking/NetworkSetting.swift
  iOS/SideDishApp/SideDishApp/Utilities/Networking/NetworkUseCase.swift
  iOS/SideDishApp/SideDishApp/ViewController.swift
  iOS/SideDishApp/SideDishApp/ViewControllers/LoginViewController.swift
  iOS/SideDishApp/SideDishApp/ViewControllers/MenuViewController.swift
  iOS/SideDishApp/SideDishApp/Views/Components/MenuTableViewCell.swift
  iOS/SideDishApp/SideDishApp/Views/MenuTableView.swift
Labels: iOS

#28 [#18] 컴포넌트 계층 구조로 파일 디렉토리 변경
  FE/my-app/public/index.html
  FE/my-app/public/logo192.png
  FE/my-app/public/logo512.png
  FE/my-app/public/manifest.json
  FE/my-app/src/App.css
  FE/my-app/src/App.js
  FE/my-app/src/App.jsx
  FE/my-app/src/App.test.js
  FE/my-app/src/components/Header/Header.jsx
  FE/my-app/src/components/Header/LocalNavBar.jsx
  FE/my-app/src/components/Header/Logo.jsx
  FE/my-app/src/components/Header/MenuBar/Category.jsx
  FE/my-app/src/components/Header/MenuBar/Item.jsx
  FE/my-app/src/components/Header/MenuBar/MenuBar.jsx
  FE/my-app/src/components/Header/MenuBar/SubList.jsx
  FE/my-app/src/components/Header/SearchBar.jsx
  FE/my-app/src/components/MoreButton.jsx
  FE/my-app/src/components/ProductDetail/CartButton.jsx
  FE/my-app/src/components/ProductDetail/Images/Images.jsx
  FE/my-app/src/components/ProductDetail/Images/ThumbImage.jsx
  FE/my-app/src/components/ProductDetail/Images/TopImage.jsx
  FE/my-app/src/components/ProductDetail/Info/Description.jsx
  FE/my-app/src/components/ProductDetail/Info/Info.jsx
  FE/my-app/src/components/ProductDetail/Info/Price.jsx
  FE/my-app/src/components/ProductDetail/Info/Title.jsx
  FE/my-app/src/components/ProductDetail/ProductDetail.jsx
  FE/my-app/src/components/ProductDetail/Selector.jsx
  FE/my-app/src/components/ProductDetail/TotalPrice.jsx
  FE/my-app/src/components/ProductList/ProductList.jsx
  FE/my-app/src/components/ProductList/Slider/NavButton.jsx
  FE/my-app/src/components/ProductList/Slider/Product/Badge.jsx
  FE/my-app/src/components/ProductList/Slider/Product/Image.jsx
  FE/my-app/src/components/ProductList/Slider/Product/Price.jsx
  FE/my-app/src/components/ProductList/Slider/Product/Product.jsx
  FE/my-app/src/components/ProductList/Slider/Product/Title.jsx
  FE/my-app/src/components/ProductList/Slider/Slider.jsx
  FE/my-app/src/components/ProductList/Title.jsx
  FE/my-app/src/index.css
  FE/my-app/src/index.jsx
  FE/my-app/src/logo.svg
  FE/my-app/src/setupTests.js
Labels: FE, enhancement

#33 [BE] 클라이언트에 데이터 제공
  BE/src/main/java/com/codesquad/sidedish06/SideDish06Application.java
  BE/src/main/java/com/codesquad/sidedish06/controller/DetailController.java
  BE/src/main/java/com/codesquad/sidedish06/controller/MainController.java
  BE/src/main/java/com/codesquad/sidedish06/controller/OverviewController.java
  BE/src/main/java/com/codesquad/sidedish06/controller/SaveController.java
  BE/src/main/java/com/codesquad/sidedish06/dao/DetailDao.java
  BE/src/main/java/com/codesquad/sidedish06/dao/OverviewDao.java
  BE/src/main/java/com/codesquad/sidedish06/domain/dto/RequestDetail.java
  BE/src/main/java/com/codesquad/sidedish06/domain/dto/RequestOverview.java
  BE/src/main/java/com/codesquad/sidedish06/domain/dto/ResponseDetail.java
  BE/src/main/java/com/codesquad/sidedish06/domain/dto/ResponseOverview.java
  BE/src/main/java/com/codesquad/sidedish06/domain/dto/ResponseOverviewData.java
  BE/src/main/java/com/codesquad/sidedish06/domain/entity/Babchan.java
  BE/src/main/java/com/codesquad/sidedish06/domain/entity/Badge.java
  BE/src/main/java/com/codesquad/sidedish06/domain/entity/Delivery.java
  BE/src/main/java/com/codesquad/sidedish06/domain/entity/DetailSection.java
  BE/src/main/java/com/codesquad/sidedish06/domain/entity/Price.java
  BE/src/main/java/com/codesquad/sidedish06/domain/entity/ThumbImage.java
  BE/src/main/java/com/codesquad/sidedish06/service/DetailService.java
  BE/src/main/java/com/codesquad/sidedish06/service/DetailServiceImpl.java
  BE/src/main/java/com/codesquad/sidedish06/service/OverviewService.java
  BE/src/main/java/com/codesquad/sidedish06/service/OverviewServiceImpl.java
  BE/src/main/java/com/codesquad/sidedish06/utils/JsonUtils.java
  BE/src/main/java/com/codesquad/sidedish06/utils/UrlUtils.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/schema.sql
Labels: BE

#34 Be/feature/oauth
  BE/.gitignore
  BE/build.gradle
  BE/src/main/java/com/codesquad/sidedish06/config/PropertyConfig.java
  BE/src/main/java/com/codesquad/sidedish06/config/WebConfig.java
  BE/src/main/java/com/codesquad/sidedish06/config/WebInitializer.java
  BE/src/main/java/com/codesquad/sidedish06/controller/LoginController.java
  BE/src/main/java/com/codesquad/sidedish06/domain/dto/GithubTokenDto.java
  BE/src/main/java/com/codesquad/sidedish06/service/LoginService.java
Labels: BE

#35 [#32] chore ✨​ war 생성하기 위한 gradle 설정 변경
  BE/build.gradle
Labels: BE, bug

#39 [#26] 슬라이더 기능 구현
  FE/my-app/package-lock.json
  FE/my-app/package.json
  FE/my-app/public/images/logo.png
  FE/my-app/src/App.jsx
  FE/my-app/src/components/Header/Logo.jsx
  FE/my-app/src/components/Header/MenuBar/Category.jsx
  FE/my-app/src/components/Header/MenuBar/MenuBar.jsx
  FE/my-app/src/components/Header/logo.svg
  FE/my-app/src/components/ProductList/Carousel/Carousel.jsx
  FE/my-app/src/components/ProductList/Carousel/Product/Badge.jsx
  FE/my-app/src/components/ProductList/Carousel/Product/Image.jsx
  FE/my-app/src/components/ProductList/Carousel/Product/Price.jsx
  FE/my-app/src/components/ProductList/Carousel/Product/Product.jsx
  FE/my-app/src/components/ProductList/Carousel/Product/Title.jsx
  FE/my-app/src/components/ProductList/Carousel/arrow.svg
  FE/my-app/src/components/ProductList/ProductList.jsx
  FE/my-app/src/components/ProductList/Slider/NavButton.jsx
  FE/my-app/src/components/ProductList/Slider/Slider.jsx
  FE/my-app/src/components/ProductList/Title.jsx
Labels: FE

#41 [iOS] 디스크에 이미지 캐시 기능 구현
  .gitignore
  iOS/SideDishApp/SideDishApp.xcodeproj/project.pbxproj
  iOS/SideDishApp/SideDishApp/Base.lproj/Main.storyboard
  iOS/SideDishApp/SideDishApp/Info.plist
  iOS/SideDishApp/SideDishApp/Models/AllMenu.swift
  iOS/SideDishApp/SideDishApp/Utilities/ImageLoader/ImageCache.swift
  iOS/SideDishApp/SideDishApp/Utilities/ImageLoader/ImageLoader.swift
  iOS/SideDishApp/SideDishApp/Utilities/Networking/NetworkManager.swift
  iOS/SideDishApp/SideDishApp/Utilities/Networking/NetworkSetting.swift
  iOS/SideDishApp/SideDishApp/Utilities/Networking/NetworkUseCase.swift
  iOS/SideDishApp/SideDishApp/ViewControllers/LoginViewController.swift
  iOS/SideDishApp/SideDishApp/ViewControllers/MenuViewController.swift
  iOS/SideDishApp/SideDishApp/Views/Components/MenuHeaderView.swift
  iOS/SideDishApp/SideDishApp/Views/Components/MenuTableViewCell.swift
  iOS/SideDishApp/SideDishApp/Views/Components/SectionHeaderTapGestureRecognizer.swift
Labels: iOS

#42 [iOS] 메뉴 상세화면과 기능 구현
  iOS/SideDishApp/SideDishApp.xcodeproj/project.pbxproj
  iOS/SideDishApp/SideDishApp/Base.lproj/Main.storyboard
  iOS/SideDishApp/SideDishApp/Models/MenuDetail.swift
  iOS/SideDishApp/SideDishApp/Utilities/ImageLoader/ImageLoader.swift
  iOS/SideDishApp/SideDishApp/Utilities/Networking/NetworkUseCase.swift
  iOS/SideDishApp/SideDishApp/ViewControllers/DetailViewController.swift
  iOS/SideDishApp/SideDishApp/ViewControllers/LoginViewController.swift
  iOS/SideDishApp/SideDishApp/ViewControllers/MenuViewController.swift
  iOS/SideDishApp/SideDishApp/Views/Components/ContentsTitleLabel.swift
  iOS/SideDishApp/SideDishApp/Views/Components/DescriptionLabel.swift
  iOS/SideDishApp/SideDishApp/Views/Components/MenuTableViewCell.swift
Labels: iOS

#44 [#43] feat :rocket: : OAuth 로그인 후 메인으로 리다이렉트 기능 구현
  BE/src/main/java/com/codesquad/sidedish06/config/GithubPropertyConfig.java
  BE/src/main/java/com/codesquad/sidedish06/controller/LoginController.java
  BE/src/main/java/com/codesquad/sidedish06/service/LoginService.java
  BE/src/main/java/com/codesquad/sidedish06/utils/UrlUtils.java
  BE/src/main/resources/application.properties
Labels: BE

#45 [#20] 상세페이지 기능 구현
  FE/my-app/src/App.jsx
  FE/my-app/src/assets/arrow.svg
  FE/my-app/src/assets/logo.svg
  FE/my-app/src/assets/spinner.svg
  FE/my-app/src/components/GlobalStyle.jsx
  FE/my-app/src/components/Header/Header.jsx
  FE/my-app/src/components/Header/Logo.jsx
  FE/my-app/src/components/Header/MenuBar/MenuBar.jsx
  FE/my-app/src/components/Header/SearchBar.jsx
  FE/my-app/src/components/Header/logo.svg
  FE/my-app/src/components/MoreButton.jsx
  FE/my-app/src/components/Placeholder.jsx
  FE/my-app/src/components/ProductDetail/CartButton.jsx
  FE/my-app/src/components/ProductDetail/Images/Images.jsx
  FE/my-app/src/components/ProductDetail/Images/ThumbImage.jsx
  FE/my-app/src/components/ProductDetail/Images/TopImage.jsx
  FE/my-app/src/components/ProductDetail/Info/Description.jsx
  FE/my-app/src/components/ProductDetail/Info/Info.jsx
  FE/my-app/src/components/ProductDetail/Info/Price.jsx
  FE/my-app/src/components/ProductDetail/Info/Title.jsx
  FE/my-app/src/components/ProductDetail/ProductDetail.jsx
  FE/my-app/src/components/ProductDetail/ProductImages/ProductImages.jsx
  FE/my-app/src/components/ProductDetail/ProductImages/ThumbImages.jsx
  FE/my-app/src/components/ProductDetail/ProductImages/TopImage.jsx
  FE/my-app/src/components/ProductDetail/ProductInfo/Details.jsx
  FE/my-app/src/components/ProductDetail/ProductInfo/Price.jsx
  FE/my-app/src/components/ProductDetail/ProductInfo/ProductInfo.jsx
  FE/my-app/src/components/ProductDetail/ProductInfo/Title.jsx
  FE/my-app/src/components/ProductDetail/Selector.jsx
  FE/my-app/src/components/ProductDetail/TotalPrice.jsx
  FE/my-app/src/components/ProductList/Carousel/Carousel.jsx
  FE/my-app/src/components/ProductList/Carousel/Product/Image.jsx
  FE/my-app/src/components/ProductList/Carousel/Product/Product.jsx
  FE/my-app/src/components/ProductList/ProductList.jsx
  FE/my-app/src/utils/animation.js
  FE/my-app/src/utils/mockData.js
  FE/my-app/src/utils/useFetch.js
Labels: FE

#49 [#47] fix :pushpin:​ : 리다이렉트 URL 수정
  BE/src/main/java/com/codesquad/sidedish06/utils/UrlUtils.java
Labels: BE, bug

#53 [#52] feat :rocket: : 로그인 Response header 추가
  BE/src/main/java/com/codesquad/sidedish06/controller/LoginController.java
Labels: BE

#54 [BE] 배포를 위한 master PR
  BE/.gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/com/codesquad/sidedish06/SideDish06Application.java
  BE/src/main/java/com/codesquad/sidedish06/config/GithubPropertyConfig.java
  BE/src/main/java/com/codesquad/sidedish06/config/WebConfig.java
  BE/src/main/java/com/codesquad/sidedish06/config/WebInitializer.java
  BE/src/main/java/com/codesquad/sidedish06/controller/DetailController.java
  BE/src/main/java/com/codesquad/sidedish06/controller/LoginController.java
  BE/src/main/java/com/codesquad/sidedish06/controller/OverviewController.java
  BE/src/main/java/com/codesquad/sidedish06/controller/SaveController.java
  BE/src/main/java/com/codesquad/sidedish06/controller/UrlController.java
  BE/src/main/java/com/codesquad/sidedish06/dao/DetailDao.java
  BE/src/main/java/com/codesquad/sidedish06/dao/MenuTypeDao.java
  BE/src/main/java/com/codesquad/sidedish06/dao/OverviewDao.java
  BE/src/main/java/com/codesquad/sidedish06/domain/dto/GithubTokenDto.java
  BE/src/main/java/com/codesquad/sidedish06/domain/dto/RequestDetail.java
  BE/src/main/java/com/codesquad/sidedish06/domain/dto/RequestOverview.java
  BE/src/main/java/com/codesquad/sidedish06/domain/dto/ResponseBadge.java
  BE/src/main/java/com/codesquad/sidedish06/domain/dto/ResponseDetail.java
  BE/src/main/java/com/codesquad/sidedish06/domain/dto/ResponseOverview.java
  BE/src/main/java/com/codesquad/sidedish06/domain/dto/ResponseOverviewData.java
  BE/src/main/java/com/codesquad/sidedish06/domain/entity/Babchan.java
  BE/src/main/java/com/codesquad/sidedish06/domain/entity/Badge.java
  BE/src/main/java/com/codesquad/sidedish06/domain/entity/Delivery.java
  BE/src/main/java/com/codesquad/sidedish06/domain/entity/DetailSection.java
  BE/src/main/java/com/codesquad/sidedish06/domain/entity/FoodType.java
  BE/src/main/java/com/codesquad/sidedish06/domain/entity/Price.java
  BE/src/main/java/com/codesquad/sidedish06/domain/entity/ThumbImage.java
  BE/src/main/java/com/codesquad/sidedish06/service/DetailService.java
  BE/src/main/java/com/codesquad/sidedish06/service/DetailServiceImpl.java
  BE/src/main/java/com/codesquad/sidedish06/service/LoginService.java
  BE/src/main/java/com/codesquad/sidedish06/service/OverviewService.java
  BE/src/main/java/com/codesquad/sidedish06/service/OverviewServiceImpl.java
  BE/src/main/java/com/codesquad/sidedish06/utils/DaoUtils.java
  BE/src/main/java/com/codesquad/sidedish06/utils/JsonUtils.java
  BE/src/main/java/com/codesquad/sidedish06/utils/UrlUtils.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/data.sql
  BE/src/main/resources/github.properties
  BE/src/main/resources/schema.sql
  BE/src/test/java/com/codesquad/sidedish06/SideDish06ApplicationTests.java
  README.md
Labels: BE

#55 [#48] 서버 API에 맞춰 코드 리팩토링
  FE/my-app/.env
  FE/my-app/src/App.jsx
  FE/my-app/src/components/Header/Header.jsx
  FE/my-app/src/components/Header/LocalNavBar/Item.jsx
  FE/my-app/src/components/Header/LocalNavBar/LocalNavBar.jsx
  FE/my-app/src/components/Header/Logo.jsx
  FE/my-app/src/components/Header/MenuBar/Category.jsx
  FE/my-app/src/components/Header/MenuBar/Item.jsx
  FE/my-app/src/components/Header/MenuBar/MenuBar.jsx
  FE/my-app/src/components/Header/SearchBar.jsx
  FE/my-app/src/components/MoreButton.jsx
  FE/my-app/src/components/Placeholder.jsx
  FE/my-app/src/components/ProductDetail/CartButton.jsx
  FE/my-app/src/components/ProductDetail/ProductDetail.jsx
  FE/my-app/src/components/ProductDetail/ProductImages/ProductImages.jsx
  FE/my-app/src/components/ProductDetail/ProductImages/ThumbImages.jsx
  FE/my-app/src/components/ProductDetail/ProductImages/TopImage.jsx
  FE/my-app/src/components/ProductDetail/ProductInfo/Details.jsx
  FE/my-app/src/components/ProductDetail/ProductInfo/Price.jsx
  FE/my-app/src/components/ProductDetail/ProductInfo/ProductInfo.jsx
  FE/my-app/src/components/ProductDetail/ProductInfo/Title.jsx
  FE/my-app/src/components/ProductDetail/Selector.jsx
  FE/my-app/src/components/ProductDetail/TotalPrice.jsx
  FE/my-app/src/components/ProductList/Carousel/Carousel.jsx
  FE/my-app/src/components/ProductList/Carousel/Product/Badge.jsx
  FE/my-app/src/components/ProductList/Carousel/Product/Image.jsx
  FE/my-app/src/components/ProductList/Carousel/Product/Price.jsx
  FE/my-app/src/components/ProductList/Carousel/Product/Product.jsx
  FE/my-app/src/components/ProductList/Carousel/Product/Title.jsx
  FE/my-app/src/components/ProductList/ProductList.jsx
  FE/my-app/src/components/ProductList/Title.jsx
  FE/my-app/src/constants/constants.js
  FE/my-app/src/utils/mockData.js
  FE/my-app/src/utils/useFetch.js
Labels: FE

#61 [iOS] GitHub 로그인 기능
  iOS/SideDishApp/SideDishApp.xcodeproj/project.pbxproj
  iOS/SideDishApp/SideDishApp/Assets.xcassets/logo.imageset/Contents.json
  iOS/SideDishApp/SideDishApp/Assets.xcassets/logo.imageset/logo.png
  iOS/SideDishApp/SideDishApp/Base.lproj/Main.storyboard
  iOS/SideDishApp/SideDishApp/Info.plist
  iOS/SideDishApp/SideDishApp/Models/AllMenu.swift
  iOS/SideDishApp/SideDishApp/Models/MenuDetail.swift
  iOS/SideDishApp/SideDishApp/Utilities/Extensions/ExtendedUIColor.swift
  iOS/SideDishApp/SideDishApp/Utilities/Networking/NetworkSetting.swift
  iOS/SideDishApp/SideDishApp/Utilities/Networking/NetworkUseCase.swift
  iOS/SideDishApp/SideDishApp/ViewControllers/DetailViewController.swift
  iOS/SideDishApp/SideDishApp/ViewControllers/GithubLoginViewController.swift
  iOS/SideDishApp/SideDishApp/ViewControllers/LoginViewController.swift
  iOS/SideDishApp/SideDishApp/ViewControllers/MenuViewController.swift
  iOS/SideDishApp/SideDishApp/Views/Components/MenuTableViewCell.swift
Labels: iOS
